import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div  className="h-20 z-10 bg-white sticky top-0"><Navbar/></div>
        {children}
       <Footer/>
        </body>
    </html>
  );
}
